# Generated by Django 5.2.8 on 2025-11-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_filelearning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileLearning',
        ),
    ]
