# Generated by Django 5.2.8 on 2025-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва файлу')),
                ('file', models.FileField(upload_to='learning_materials/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
